/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetypesoftware.eatalian.domain.accounts;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFs16/2roSy+FA= >>
// ----------- >>

/**
* Address of the customer.
*/

@Embeddable
// ----------- << class.annotations@AAAAAAFs16/2roSy+FA= >>
// ----------- >>
public class Address {
    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFs17ADqITc6r0= >>
    // ----------- >>
    private String streetAndNo;

    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFs17Ai34TjqVo= >>
    // ----------- >>
    private String city;

    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFs17Awn4TqblA= >>
    // ----------- >>
    private String postalCode;

    @Column
    // ----------- << attribute.annotations@AAAAAAFs17BEyITx+FM= >>
    // ----------- >>
    private String country;

    @Column
    // ----------- << attribute.annotations@AAAAAAFs17BhnIT4+zM= >>
    // ----------- >>
    private String floor;

    public String getStreetAndNo() {
        return streetAndNo;
    }

    public String getCity() {
        return city;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public String getCountry() {
        return country;
    }

    public String getFloor() {
        return floor;
    }

    public Address setStreetAndNo(String streetAndNo) {
        this.streetAndNo = streetAndNo;
        return this;
    }

    public Address setCity(String city) {
        this.city = city;
        return this;
    }

    public Address setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
    }

    public Address setCountry(String country) {
        this.country = country;
        return this;
    }

    public Address setFloor(String floor) {
        this.floor = floor;
        return this;
    }

// ----------- << class.extras@AAAAAAFs16/2roSy+FA= >>
// ----------- >>
}