/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetypesoftware.eatalian.domain.catalogue;

import java.util.*;
import java.time.*;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;


// ----------- << imports@AAAAAAFs15c0YX/A4As= >>
// ----------- >>

@Entity
@ApiModel(description = "A set of products belongs to a Category, while Categories can additionaly belong to a parent Category.")
// ----------- << class.annotations@AAAAAAFs15c0YX/A4As= >>
// ----------- >>
public class Category {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    // ----------- << id.annotations@AAAAAAFs15c0YX/A4As= >>
    // ----------- >>
    private Long id;

    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFs15d7GIAU9Ik= >>
    // ----------- >>
    private String name;

    @Column
    // ----------- << attribute.annotations@AAAAAAFs15eJ0YAbiZc= >>
    // ----------- >>
    private String description;

    @OneToMany(mappedBy = "category")
    // ----------- << attribute.annotations@AAAAAAFs15idfoA8nB8= >>
    // ----------- >>
    private Set<Product> products = new HashSet<>();

    @OneToMany(mappedBy = "parent")
    // ----------- << attribute.annotations@AAAAAAFs15lm2oC9jiM= >>
    // ----------- >>
    private Set<Category> subCategories = new HashSet<>();

    @ManyToOne
    @JoinColumn(name = "parent_id")
    @JsonIgnore
    // ----------- << attribute.annotations@AAAAAAFs15lm2oC8Iwc= >>
    // ----------- >>
    private Category parent;

    // ----------- << getId.annotations@AAAAAAFs15c0YX/A4As= >>
    // ----------- >>
    public Long getId(){
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public Set<Product> getProducts() {
        return products;
    }

    public Set<Category> getSubCategories() {
        return subCategories;
    }

    public Category getParent() {
        return parent;
    }

    public Category setName(String name) {
        this.name = name;
        return this;
    }

    public Category setDescription(String description) {
        this.description = description;
        return this;
    }

    public Category setParent(Category parent) {
        this.parent = parent;
        return this;
    }

    public Category linkProducts(Product _products) {
        if (_products != null) {
            _products.unlinkCategory();
            _products.setCategory(this);
            getProducts().add(_products);
        }
        return this;
    }

    public Category linkSubCategories(Category _subCategories) {
        if (_subCategories != null) {
            _subCategories.unlinkParent();
            _subCategories.setParent(this);
            getSubCategories().add(_subCategories);
        }
        return this;
    }

    public Category linkParent(Category _parent) {
        if (_parent != null) {
            _parent.getSubCategories().add(this);
        }

        unlinkParent();
        setParent(_parent);
        return this;
    }

    public Category unlinkProducts(Product _products) {
        if (_products != null) {
            _products.setCategory(null);
            getProducts().remove(_products);
        }
        return this;
    }

    public Category unlinkProducts(Product _products, Iterator<Product> it) {
        if (_products != null) {
            _products.setCategory(null);
            it.remove();
        }
        return this;
    }

    public Category unlinkSubCategories(Category _subCategories) {
        if (_subCategories != null) {
            _subCategories.setParent(null);
            getSubCategories().remove(_subCategories);
        }
        return this;
    }

    public Category unlinkSubCategories(Category _subCategories, Iterator<Category> it) {
        if (_subCategories != null) {
            _subCategories.setParent(null);
            it.remove();
        }
        return this;
    }

    public Category unlinkParent() {
        if (getParent() != null) {
            getParent().getSubCategories().remove(this);
            setParent(null);
        }
        return this;
    }

    // ----------- << equals.annotations@AAAAAAFs15c0YX/A4As= >>
    // ----------- >>
    @Override
    public boolean equals(Object obj) {
        if (super.equals(obj)) return true;
        if (getId() == null) return false;
        return obj instanceof Category && (getId().equals(((Category) obj).getId()));
    }

    // ----------- << hashCode.annotations@AAAAAAFs15c0YX/A4As= >>
    // ----------- >>
    @Override
    public int hashCode() {
        return 248;
    }

// ----------- << class.extras@AAAAAAFs15c0YX/A4As= >>

    public Category() {
    }

    public Category(@NotNull String name) {
        this.name = name;
    }

// ----------- >>
}