/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package com.archetypesoftware.eatalian.controllers;

import com.archetypesoftware.eatalian.domain.orders.GroupRequest;
import com.archetypesoftware.eatalian.services.GroupRequestService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@Transactional
@RestController
@RequestMapping("/groupRequests")
public class GroupRequestController {
    private static final Logger logger = LoggerFactory.getLogger(GroupRequestController.class);

    private final GroupRequestService service;

    @Autowired
    public GroupRequestController(GroupRequestService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<GroupRequest> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public GroupRequest findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public GroupRequest create(@RequestBody @Valid GroupRequest entity) {
        return service.save(entity);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}