/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package com.archetypesoftware.eatalian.controllers;

import com.archetypesoftware.eatalian.domain.orders.ProductRequest;
import com.archetypesoftware.eatalian.services.ProductRequestService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@Transactional
@RestController
@RequestMapping("/productRequests")
public class ProductRequestController {
    private static final Logger logger = LoggerFactory.getLogger(ProductRequestController.class);

    private final ProductRequestService service;

    @Autowired
    public ProductRequestController(ProductRequestService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<ProductRequest> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public ProductRequest findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public ProductRequest create(@RequestBody @Valid ProductRequest entity) {
        return service.save(entity);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}