/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package com.archetypesoftware.eatalian.services;

import com.archetypesoftware.eatalian.domain.orders.ProductRequest;
import com.archetypesoftware.eatalian.repositories.ProductRequestRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
public class ProductRequestService {
    private static final Logger logger = LoggerFactory.getLogger(ProductRequestService.class);

    private final ProductRequestRepository repository;

    @Autowired
    public ProductRequestService(ProductRequestRepository repository) {
        this.repository = repository;
    }

    public Iterable<ProductRequest> findAll() {
        return repository.findAll();
    }

    public ProductRequest findOne(Long id) {
        return repository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find ProductRequest by " + id));
    }

    public ProductRequest save(ProductRequest entity) {
        return repository.save(entity);
    }

    public void delete(ProductRequest entity) {
        repository.delete(entity);
    }

    public void delete(Long id) {
        delete(findOne(id));
    }
}