/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetypesoftware.eatalian.domain.orders;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFs1/Drso3LG9Q= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFs1/Drso3LG9Q= >>
// ----------- >>
public enum OrderState {
    created,
    placed,
    accepted,
    preparation,
    completed,
    pendingDelivery,
    delivered,
    abandoned,
    rejected;

// ----------- << enum.extras@AAAAAAFs1/Drso3LG9Q= >>
// ----------- >>
}