/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetypesoftware.eatalian.domain.orders;

import java.util.*;
import java.time.*;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.*;
import javax.validation.constraints.*;

import com.archetypesoftware.eatalian.domain.catalogue.Product;
import com.archetypesoftware.eatalian.domain.monetary.CurrencyAmount;
// ----------- << imports@AAAAAAFs1+yrWosuGh4= >>
import java.math.BigDecimal;
// ----------- >>

@Entity
@ApiModel(description = "")
// ----------- << class.annotations@AAAAAAFs1+yrWosuGh4= >>
// ----------- >>
public class ProductRequest extends Request {
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFs1+2Iq4tfkFE= >>
    // ----------- >>
    private int quantity;

    @NotNull
    @ManyToOne
    @JoinColumn(name = "product_id")
    // ----------- << attribute.annotations@AAAAAAFs1/wMm5Zi324= >>
    // ----------- >>
    private Product product;

    public int getQuantity() {
        return quantity;
    }

    public Product getProduct() {
        return product;
    }

    public ProductRequest setQuantity(int quantity) {
        this.quantity = quantity;
        return this;
    }

    public ProductRequest setProduct(Product product) {
        this.product = product;
        return this;
    }

    public ProductRequest linkProduct(Product _product) {
        setProduct(_product);
        return this;
    }

    public ProductRequest unlinkProduct() {
        setProduct(null);
        return this;
    }

    // ----------- << equals.annotations@AAAAAAFs1+yrWosuGh4= >>
    // ----------- >>
    @Override
    public boolean equals(Object obj) {
        if (super.equals(obj)) return true;
        if (getId() == null) return false;
        return obj instanceof ProductRequest && (getId().equals(((ProductRequest) obj).getId()));
    }

    // ----------- << hashCode.annotations@AAAAAAFs1+yrWosuGh4= >>
    // ----------- >>
    @Override
    public int hashCode() {
        return 268;
    }

    @Override
    // ----------- << method.annotations@AAAAAAFs2EGVixtRAIk= >>
    // ----------- >>
    public CurrencyAmount getTotalPrice() {
    // ----------- << method.body@AAAAAAFs2EGVixtRAIk= >>
        CurrencyAmount productPrice = getProduct().getPrice();
        return CurrencyAmount
                .of(productPrice.getAmount().multiply(BigDecimal.valueOf(quantity)),
                        productPrice.getCurrency());
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFs1+yrWosuGh4= >>
// ----------- >>
}